osx_image: xcode8.2
language: objective-c
xcode_workspace: Movies.xcworkspace
xcode_scheme: Movies
# notifications:
#   webhooks: http://appsnap-api-90ead5a9.9670d3e0.svc.dockerapp.io/builds
before_install:
- pod install
- gem install fastlane --no-ri --no-doc --no-document
script: fastlane snapshot --verbose --derived_data_path derivedData --skip_open_summary
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - ./screenshots
      - ./derivedData/Logs/Test
    debug: true
